---
    - name: install apache
      ansible.builtin.apt:
        name: "{{ training_apache_packages }}"
        state: latest
        update_cache: false
      vars:
        training_apache_packages:
          - apache2
          - apache2-utils
    - name: show variable tasks
      ansible.builtin.debug:
        var: training_apache_packages
