---
- name: Install Apache
  hosts: training
  become: true
  gather_facts: true
  vars:
    training_apache_packages:
      - apache2
      - apache2-utils
      - apache2-doc

  pre_tasks:
    - name: show variable pre
      ansible.builtin.debug:
        var: training_apache_packages

  roles:

  tasks:
    - name: install apache (play)
      ansible.builtin.import_tasks: install_apache.yml


  post_tasks:
    - name: show variable post
      ansible.builtin.debug:
        var: training_apache_packages

- name: Test Apache
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: test apache
      ansible.builtin.uri:
        url: http://ghilling.training.hilling.de
      register: apache_uri_result
    - name: show variable
      ansible.builtin.debug:
        var: training_apache_packages
